FullStackCRUDAppWithOnetoManyRelationship/Models/DomainModels/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels
{
    public class Teacher
    {
        public Teacher() => new HashSet<Teacher>();//constructor for initialized collection
        public int TeacherId { get; set; } //primary key

        [Display(Name = "First Name")]
        [StringLength(100, ErrorMessage = "First Name may not exceed 100 characters")]
        [Required(ErrorMessage = "Enter a first name")]
        public string FirstName { get; set; }


        [Display(Name = "Last Name")]
        [StringLength(100, ErrorMessage = "Last Name may not exceed 100 characters")]
        [Required(ErrorMessage = "Last Name may not exceed 100 characters")]
        public string LastName { get; set; }

        //readonly string Properties;
        public string FullName => $"{FirstName} {LastName}";


        public ICollection<Class> Classes { get; set; }
    }
}

FullStackCRUDAppWithOnetoManyRelationship/Controllers/ClassController.cs
using FullStackCRUDAppWithOnetoManyRelationship.Models.DataLayer;
using FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels;
using Microsoft.AspNetCore.Mvc;

namespace FullStackCRUDAppWithOnetoManyRelationship.Controllers
{
    public class ClassController : Controller
    {
        //initialize class Repository
        private Repository<Class> Classes { get; set; }
        private Repository<Teacher> teachers { get; set; }
        private Repository<Day> days { get; set; }

        public ClassController(ScheduleDBContext ctx)
        {
            //initialize class Db-context constructor
            Classes = new Repository<Class>(ctx);
            teachers = new Repository<Teacher>(ctx);
            days = new Repository<Day>(ctx);
        }

        //Home redirect Route
        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add()
        {
            this.LoadViewBag("Add");
            return View("AddEdith", new Class());
        }

        //Post/Save into db 
        [HttpPost]
        public IActionResult Add(Class c)
        {
            bool isAdd = c.ClassId == 0;

            if (ModelState.IsValid)
            {
                //insert in class c
                if (isAdd)
                    Classes.Insert(c);
                else Classes.Update(c);
            }
            else
            {
                //if not valid
                string operation = (isAdd) ? "add" : "Edith";
                this.LoadViewBag(operation);
                return View("AddEdith", c);
            }

            return View();
        }

        //Edit Class

        [HttpGet]
        public ViewResult Edit(int id)
        {
            this.LoadViewBag("Edith");
            var c = this.GetClass(id);
            return View("AddEdith", c);
        }


        //Delete a Class
        [HttpGet]
        public ViewResult Delete(int id)
        {
            var c = this.GetClass(id);
            return View(c);

        }


        //helper method
        private Class GetClass(int id)
        {
            var classOptions = new QueryOptions<Class>
            {
                Includes = "Teacher, Day"
            };
            return Classes.Get(classOptions) ?? new Class();
        }


        private void LoadViewBag(string operation)
        {
            ViewBag.Days = days.List(new QueryOptions<Day>
            {
                OrderBy = d => d.DayId,

            });
            ViewBag.Teachers = teachers.List(new QueryOptions<Teacher>
            {
                OrderBy = t => t.LastName
            });
            ViewBag.Operation = operation;
        }

    }
}

FullStackCRUDAppWithOnetoManyRelationship/Controllers/TeacherController.cs
using FullStackCRUDAppWithOnetoManyRelationship.Models.DataLayer;
using FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels;
using Microsoft.AspNetCore.Mvc;

namespace FullStackCRUDAppWithOnetoManyRelationship.Controllers
{
    public class TeacherController : Controller
    {
        //initialize the repository
        private Repository<Teacher> teachers { get; set; }

        //initialize the db context
        public TeacherController(ScheduleDBContext ctx) => teachers = new Repository<Teacher>(ctx);


        public ViewResult Index()
        {
            var options = new QueryOptions<Teacher>
            {
                OrderBy = t => t.LastName
            };

            return View(teachers.List(options));
        }


        //Add Teachers
        [HttpGet]
        public ViewResult Add() => View();

        [HttpPost]
        public IActionResult Add(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                teachers.Insert(teacher);
                teachers.save();
                return RedirectToAction("Index");
            }
            else
            {
                return View(teacher);
            }

        }


        //Delete Teacher

        [HttpGet]
        public ViewResult Delete(int id) => View(teachers);

        //Delete a teacher
        [HttpPost]
        public RedirectToActionResult Delete(Teacher teacher)
        {

            teachers.Delete(teacher);
            teachers.save();
            return RedirectToAction("Index");

        }

    }
}

FullStackCRUDAppWithOnetoManyRelationship/Views/Teacher/Add.cshtml
@model Teacher
@{
    ViewBag.Title = "Add Teacher";
}

<h1 class="display-4">Add Teacher</h1>

<form asp-action="Add" asp-controller="Teacher" method="post">
<div asp-validation-summary="All" class="text-danger"></div>

<div class="mb-3">
    <label asp-for="LastName" class="form-label"></label>
    <input asp-for="LastName" class="form-control" />
</div>

<button type="submit" class="btn-dark">Save</button>
<a asp-action="Index" asp-controller="Teacher" class="btn-outline-dark">Cancel</a>
</form>

FullStackCRUDAppWithOnetoManyRelationship/Views/Teacher/Delete.cshtml
@using FullStackCRUDAppWithOnetoManyRelationship.Models.DomainModels;
@using Microsoft.AspNetCore.Mvc;
@model Teacher

@{
    ViewBag.Title = "Delete Teacher";
}

<h1 class="display-4">@ViewBag.Title</h1>

<ul class="list-group mb-2">
    <li class="list-group-item">
        @Model.FullName
    </li>
</ul>

<form asp-action="Delete" method="post">
    <input asp-for="TeacherId" type="hidden" />
    <button type="submit" class="btn btn-dark">Delete</button>
    <a asp-action="Index" asp-controller="Teacher" class="btn-outline-dark">Cancel</a>
</form>

FullStackCRUDAppWithOnetoManyRelationship/Views/Teacher/Index.cshtml
@model IEnumerable<Teacher>
@{
    ViewBag.Title = "Teachers";
}

<div class="text-center">
    <h1 class="display-4">Teachers</h1>
</div>

<a asp-action="Add" asp-controller="Class">Add Teacher</a>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
                        
        </tr>
    </thead>
    <tbody>
        @foreach (Teacher teacher in Model)
        {
            <tr>
                <td>@teacher.FirstName</td>
                <td>@teacher.LastName</td>
                
                
                <td>
                    
                    <a asp-action="Delete" asp-controller="Class" asp-route-id="@teacher.TeacherId" class="btn-outline-dark">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>